/**
 * Studio build.
 *
 * The studio is authored as a single JSX file with no imports, running against
 * React from a CDN. That's a deliberate constraint - it keeps the source
 * readable as one artifact and editable without a toolchain. What it should
 * NOT mean is shipping the compiler to visitors: the previous setup loaded
 * Babel Standalone plus React's development build and compiled 175KB of JSX
 * in the browser on every page view, which is roughly a second of dead time
 * and a console warning telling you not to do it.
 *
 * So: same authoring model, compiled once here. esbuild transforms the JSX
 * and minifies it; index.html loads the result alongside React's production
 * build. Nothing about how you write the app changes.
 *
 *   npm run build    compile once
 *   npm run dev      recompile on save
 */
import { build, context } from 'esbuild';
import { readFileSync, writeFileSync, statSync } from 'node:fs';

const ENTRY = 'designsystem.app.jsx';
const OUT = 'designsystem.app.js';

/** @type {import('esbuild').BuildOptions} */
const options = {
  entryPoints: [ENTRY],
  outfile: OUT,
  // NOT bundled: React and ReactDOM arrive as UMD globals from the CDN, and
  // the file has no imports of its own. We only need the JSX transform.
  bundle: false,
  loader: { '.jsx': 'jsx' },
  format: 'iife',
  target: ['es2020'],
  minify: true,
  legalComments: 'none',
  banner: {
    js: '/* Design System Studio - generated by build.mjs. Edit designsystem.app.jsx, then `npm run build`. */',
  },
};

const kb = (p) => (statSync(p).size / 1024).toFixed(1) + 'KB';

if (process.argv.includes('--watch')) {
  const ctx = await context(options);
  await ctx.watch();
  console.log(`watching ${ENTRY} -> ${OUT}`);
} else {
  await build(options);
  console.log(`built ${ENTRY} (${kb(ENTRY)}) -> ${OUT} (${kb(OUT)})`);

  // Guard against the one way this setup can bite: editing the JSX, forgetting
  // to rebuild, and shipping a stale bundle. The check runs in CI-ish contexts
  // via `npm run verify`.
  const stale = statSync(ENTRY).mtimeMs > statSync(OUT).mtimeMs;
  if (stale) {
    console.error(`WARNING: ${OUT} is older than ${ENTRY}`);
    process.exitCode = 1;
  }
}
